import React from 'react';
// component
import Visual from './Visual'
// css
import '/public/styles/reset.scss';
import '/public/styles/default.scss';



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Visual/>
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
